theme: jekyll-theme-cayman
name: "CBB752 Zimmerone Projects"
title: "Biomedical Data Science: Mining and Modeling"
description: "projects progress from 2017-2022"
author:
  name: Susanna Liu
  email: susanna.liu@yale.edu
